AdventureWorks.CustomerCarePortal.Web/Models/ErrorViewModel.cs
namespace AdventureWorks.CustomerCarePortal.Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AdventureWorks.CustomerCarePortal.Web/Controllers/CustomerController.cs
using Microsoft.AspNetCore.Mvc;

namespace AdventureWorks.CustomerCarePortal.Web.Controllers
{
    public class CustomerController : Controller
    {


        
        
        public IActionResult Index()
        {
            return View();
        }
    }
}

AdventureWorks.CustomerCarePortal.Web/Controllers/HomeController.cs
using AdventureWorks.CustomerCarePortal.Web.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace AdventureWorks.CustomerCarePortal.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Test()
        {
            return View();
        }
        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AdventureWorks.CustomerCarePortal.Web/Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;

namespace AdventureWorks.CustomerCarePortal.Web.Controllers
{
    public class OrderController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

AdventureWorks.CustomerCarePortal.Web/Views/Customer/Index.cshtml
@{
    var Modil = new
    {
        id = 100,
        fName = "john",
        lName = "public",
        email = "john.q.public@gmail.com",
        rewardLevel = "gold",
        addressNum = 6423,
        street = "wall St",
        city = "mobile",
        state = "AL",
        zip = "35126-1234",
        phoneNumber = "555-555-5555"
    };
    ViewData["Title"] = "Customer Details";
}
<div id="customer-details-main">
    <div class="row ">
        <div class="col-2 offset-4 ">
            <svg xmlns="http://www.w3.org/2000/svg" width="36" height="36" fill="orange" class="bi bi-trophy-fill" viewBox="0 0 16 16">
                <path d="M2.5.5A.5.5 0 0 1 3 0h10a.5.5 0 0 1 .5.5c0 .538-.012 1.05-.034 1.536a3 3 0 1 1-1.133 5.89c-.79 1.865-1.878 2.777-2.833 3.011v2.173l1.425.356c.194.048.377.135.537.255L13.3 15.1a.5.5 0 0 1-.3.9H3a.5.5 0 0 1-.3-.9l1.838-1.379c.16-.12.343-.207.537-.255L6.5 13.11v-2.173c-.955-.234-2.043-1.146-2.833-3.012a3 3 0 1 1-1.132-5.89A33.076 33.076 0 0 1 2.5.5zm.099 2.54a2 2 0 0 0 .72 3.935c-.333-1.05-.588-2.346-.72-3.935zm10.083 3.935a2 2 0 0 0 .72-3.935c-.133 1.59-.388 2.885-.72 3.935z" />
            </svg>
        </div>
        <div class="col-3   me-auto">
            <a href="#">Edit</a>
        </div>
        <div class="col-3  me-auto">
            <a href="#">Select</a>
        </div>
    </div>
    <div class="row ">
        <div class="col-1">
            @Modil.fName
        </div>
        <div class="col-1">
            Q
        </div>
        <div class="col-1">
            @Modil.lName
        </div>
        <div class="col-4">
        </div>
    </div>
    <div class="row ">
        <div class="col-4">
            @Modil.email
        </div>
    </div>
    <div class="row  py-3 border-bottom">
        <div class="col-4 mb-3 ">
            @Modil.phoneNumber
        </div>
    </div>
    <div class="row  ">
        <h3 class="text-primary">
            Shipping
        </h3>
    </div>
    <div class="row ">
        <div class="col-4">
            @Modil.addressNum  @Modil.street
        </div>
    </div>
    <div class="row  py-3 border-bottom">
        <div class="col-3">
            @Modil.city
        </div>
        <div class="col-3">
            @Modil.state
        </div>
        <div class="col-3 mb-3">
            @Modil.zip
        </div>
    </div>
    <div class="row  ">
        <h3 class="text-primary">
            Billing
        </h3>
    </div>
    <div class="row ">
        <div class="col-4 ">
            @Modil.addressNum  @Modil.street
        </div>
    </div>
    <div class="row  py-3 border-bottom">
        <div class="col-3 mb-3">
            @Modil.city
        </div>
        <div class="col-3">
            @Modil.state
        </div>
        <div class="col-3">
            @Modil.zip
        </div>
    </div>
    <div class="row ">
        <h3 class="text-primary">
            Recommendations
        </h3>
    </div>
    <div class="row  py-4 border-bottom ms-5">
        @for (var i = 0; i < 4; i++)
        {
            <div class="col-2 mb-3">
                <img src="~/Images/greyBox.png" />
            </div>
        }
    </div>
    <div class="row ">
        <h3 class="text-primary">
            Order History
        </h3>
    </div>
    <div class="row ms-3 ">
        <div class="col-3">
            12.21.2021
        </div>
        <div class="col-3 ">
            Open
        </div>
    </div>
    <div class="row  py-4 border-bottom ms-5">
        @for (var i = 0; i < 3; i++)
        {
            <div class="col-2 mb-3">
                <img src="~/Images/greyBox.png" />
            </div>
        }
    </div>
    <div class="row ms-3">
        <div class="col-3">
            06.88.1990
        </div>
        <div class="col-3">
            Shipped
        </div>
    </div>
    <div class="row  py-3 border-bottom ms-5">
        @for (var i = 0; i < 2; i++)
        {
            <div class="col-2 ">
                <img src="~/Images/greyBox.png" />
            </div>
        }
    </div>
</div>

AdventureWorks.CustomerCarePortal.Web/Views/Home/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<div class="mt-5">
    <div class="row">
    </div>
    <div class="input-group mt-5 mb-5">
        <input type="text" class="form-control" placeholder=" username" aria-label=" username" aria-describedby="basic-addon2">
        <div class="input-group-append">
            <button id="search-customers-button" class="btn btn-outline-secondary" type="button">Search</button>
        </div>
    </div>
</div>
<table id="example" class="display" style="width:100%">
    <thead>
        <tr>
            <th class="text-primary th-sm">Name</th>
            <th class="text-primary th-sm">Last Ordered</th>
            <th></th>
            <th id="useless-select-sort"></th>
        </tr>
    </thead>
    <tbody>
        @for (var i = 0; i < 200; i++)
        {
            <tr class="border" style="border:1px">
                <td class="">Charles Xavier</td>
                <td>04.26.1980</td>
                <td class="justify-content-end align-items-end">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="orange" class="bi bi-trophy-fill" viewBox="0 0 16 16">
                        <path d="M2.5.5A.5.5 0 0 1 3 0h10a.5.5 0 0 1 .5.5c0 .538-.012 1.05-.034 1.536a3 3 0 1 1-1.133 5.89c-.79 1.865-1.878 2.777-2.833 3.011v2.173l1.425.356c.194.048.377.135.537.255L13.3 15.1a.5.5 0 0 1-.3.9H3a.5.5 0 0 1-.3-.9l1.838-1.379c.16-.12.343-.207.537-.255L6.5 13.11v-2.173c-.955-.234-2.043-1.146-2.833-3.012a3 3 0 1 1-1.132-5.89A33.076 33.076 0 0 1 2.5.5zm.099 2.54a2 2 0 0 0 .72 3.935c-.333-1.05-.588-2.346-.72-3.935zm10.083 3.935a2 2 0 0 0 .72-3.935c-.133 1.59-.388 2.885-.72 3.935z" />
                    </svg>
                </td>
                <td><a href="#">Select</a></td>
            </tr>
            <tr class="border">
                <td>Charles Xavier</td>
                <td>04.26.1980</td>
                <td>
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="silver" class="bi bi-trophy-fill" viewBox="0 0 16 16">
                        <path d="M2.5.5A.5.5 0 0 1 3 0h10a.5.5 0 0 1 .5.5c0 .538-.012 1.05-.034 1.536a3 3 0 1 1-1.133 5.89c-.79 1.865-1.878 2.777-2.833 3.011v2.173l1.425.356c.194.048.377.135.537.255L13.3 15.1a.5.5 0 0 1-.3.9H3a.5.5 0 0 1-.3-.9l1.838-1.379c.16-.12.343-.207.537-.255L6.5 13.11v-2.173c-.955-.234-2.043-1.146-2.833-3.012a3 3 0 1 1-1.132-5.89A33.076 33.076 0 0 1 2.5.5zm.099 2.54a2 2 0 0 0 .72 3.935c-.333-1.05-.588-2.346-.72-3.935zm10.083 3.935a2 2 0 0 0 .72-3.935c-.133 1.59-.388 2.885-.72 3.935z" />
                    </svg>
                </td>
                <td><a href="#">Select</a></td>
            </tr>
            <tr class="border">
                <td>Richard Nixon</td>
                <td>04.02.1972</td>
                <td>
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="gold" class="bi bi-trophy-fill" viewBox="0 0 16 16">
                        <path d="M2.5.5A.5.5 0 0 1 3 0h10a.5.5 0 0 1 .5.5c0 .538-.012 1.05-.034 1.536a3 3 0 1 1-1.133 5.89c-.79 1.865-1.878 2.777-2.833 3.011v2.173l1.425.356c.194.048.377.135.537.255L13.3 15.1a.5.5 0 0 1-.3.9H3a.5.5 0 0 1-.3-.9l1.838-1.379c.16-.12.343-.207.537-.255L6.5 13.11v-2.173c-.955-.234-2.043-1.146-2.833-3.012a3 3 0 1 1-1.132-5.89A33.076 33.076 0 0 1 2.5.5zm.099 2.54a2 2 0 0 0 .72 3.935c-.333-1.05-.588-2.346-.72-3.935zm10.083 3.935a2 2 0 0 0 .72-3.935c-.133 1.59-.388 2.885-.72 3.935z" />
                    </svg>
                </td>
                <td><a href="#">Select</a></td>
            </tr>
            <tr class="border">
                <td>Richard Nixon</td>
                <td>04.02.1972</td>
                <td>
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="orange" class="bi bi-trophy-fill" viewBox="0 0 16 16">
                        <path d="M2.5.5A.5.5 0 0 1 3 0h10a.5.5 0 0 1 .5.5c0 .538-.012 1.05-.034 1.536a3 3 0 1 1-1.133 5.89c-.79 1.865-1.878 2.777-2.833 3.011v2.173l1.425.356c.194.048.377.135.537.255L13.3 15.1a.5.5 0 0 1-.3.9H3a.5.5 0 0 1-.3-.9l1.838-1.379c.16-.12.343-.207.537-.255L6.5 13.11v-2.173c-.955-.234-2.043-1.146-2.833-3.012a3 3 0 1 1-1.132-5.89A33.076 33.076 0 0 1 2.5.5zm.099 2.54a2 2 0 0 0 .72 3.935c-.333-1.05-.588-2.346-.72-3.935zm10.083 3.935a2 2 0 0 0 .72-3.935c-.133 1.59-.388 2.885-.72 3.935z" />
                    </svg>
                </td>
                <td><a href="#">Select</a></td>
            </tr>
            <tr class="border">
                <td>Temprance Alucard</td>
                <td>06.03.1642</td>
                <td>
                    <div class="m-auto">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="silver" class="bi bi-trophy-fill " viewBox="0 0 16 16">
                            <path d="M2.5.5A.5.5 0 0 1 3 0h10a.5.5 0 0 1 .5.5c0 .538-.012 1.05-.034 1.536a3 3 0 1 1-1.133 5.89c-.79 1.865-1.878 2.777-2.833 3.011v2.173l1.425.356c.194.048.377.135.537.255L13.3 15.1a.5.5 0 0 1-.3.9H3a.5.5 0 0 1-.3-.9l1.838-1.379c.16-.12.343-.207.537-.255L6.5 13.11v-2.173c-.955-.234-2.043-1.146-2.833-3.012a3 3 0 1 1-1.132-5.89A33.076 33.076 0 0 1 2.5.5zm.099 2.54a2 2 0 0 0 .72 3.935c-.333-1.05-.588-2.346-.72-3.935zm10.083 3.935a2 2 0 0 0 .72-3.935c-.133 1.59-.388 2.885-.72 3.935z" />
                        </svg>
                    </div>
                </td>
                <td><a href="#">Select</a></td>
            </tr>
        }
    </tbody>
    <tfoot>
        <tr class="text-primary">
            <th class="text-primary">Name</th>
            <th class="text-primary">Last Ordered</th>
            <th></th>
            <th></th>
        </tr>
    </tfoot>
</table>

AdventureWorks.CustomerCarePortal.Web/Views/Home/Test.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Test Page";
}
<h1>Test Page</h1>
@*this is a comment*@

AdventureWorks.CustomerCarePortal.Web/Views/Order/Index.cshtml
@{
    ViewData["Title"] = "Order Details";
    var Modil = new { id = 100, fName = "john", lName = "public", email = "john.q.public@gmail.com", rewardLevel = "gold",
                    addressNum = 6423, street = "wall St", city = "mobile", state = "AL", zip = "35126-1234", phoneNumber = "555-555-5555" };
    var Shrt = new { desc = "blue shirt", category = "apparel", price = 45.99, discount = 3 };
    var Pmp = new { desc = "Air Pump", category = "accessories", price = 54.23, discount = 0 };
    var Chn = new { desc = "Bike Chain", category = "parts", price = 45.99, discount = 3 };
    var Ordr = new { customer = Modil, orderDate = "1.28.2021", trackingNum = "32456241", 
                    orderNum = "2344-2344-1233", items = new List<object> { Shrt, Pmp, Chn } };
}
<div id="order-details-main">
    <div class="row">
        <div class="col-1 offset-7">
            <h4><a href="#">Edit</a></h4>
        </div>
        <div class="col-1 offset-1">
            <h4><a href="#">Cancel</a></h4>
        </div>
        <div class="col-1 offset-1 ">
            <h4><a href="#">Return</a></h4>
        </div>
    </div>
    <!--end row-->
    <div class="row py-3 border-bottom">
        <div class="col-4">
            @Modil.fName Q @Modil.lName
        </div>
        <div class="col-4">
            @Ordr.orderDate
        </div>
        <div class="col-4">
            @Ordr.orderNum
        </div>
    </div>
    <!--end row-->
    <div class="row">
        <div class="col-4">
            <h3 class="text-primary">
                Shipping
            </h3>
        </div>
        <div class="col-4 offset-4">
            <a href="#">@Ordr.trackingNum</a>
        </div>
    </div>
    <!--end row-->
    <div class="row">
        <div class="col-4">
            @Ordr.customer.addressNum @Ordr.customer.street
        </div>
    </div>
    <!--end row-->
    <div class="row pb-4 border-bottom">
        <div class="col-2">
            @Ordr.customer.city
        </div>
        <div class="col-2">
            @Ordr.customer.state
        </div>
        <div class="col-3">
            @Ordr.customer.zip
        </div>
    </div>
    <!--end row-->
    <div class="row">
        <div class="col-4">
            <h3 class="text-primary">
                Billing
            </h3>
        </div>
    </div>
    <!--end row-->
    <div class="row">
        <div class="col-4">
            @Ordr.customer.addressNum @Ordr.customer.street
        </div>
    </div>
    <!--end row-->
    <div class="row pb-4 mb-5 ">
        <div class="col-2">
            @Ordr.customer.city
        </div>
        <div class="col-2">
            @Ordr.customer.state
        </div>
        <div class="col-3">
            @Ordr.customer.zip
        </div>
    </div>
    <!--end row-->
    <div class="row">
        <div class="col-10 offset-1">
            @for (var i = 0; i < 5; i++)
            {
                <div class="row py-1 ">
                    <div class="col-2 pb-3 border-bottom">
                        <a href="#" class="text-muted"> Bike Chain</a>
                    </div>
                    <div class="col-2 border-bottom">
                        <a href="#" class="text-muted"> Parts </a>
                    </div>
                    <div class="col-2 border-bottom">
                        $59.99
                    </div>
                    <div class="col-2 border-bottom">
                        $57.99
                    </div>
                    <div class="col-2 ">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="dark" class="bi bi-trash" viewBox="0 0 16 16">
                            <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z" />
                            <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z" />
                        </svg>
                    </div>
                </div>
            }
        </div>
    </div>
    <!--end row-->
    <div class="row">
        <div class="col-6 offset-2">
            <div class="row pb-3 border-bottom">
                <div class="col-4">
                    Sub-Total
                </div>
                <div class="col-4 offset-4">
                    $167.85
                </div>
                <!--endrow-->
            </div>
            <div class="row pb-3 border-bottom">
                <div class="col-4">
                    Tax
                </div>
                <div class="col-4 offset-4">
                    $19.99
                </div>
                <!--endrow-->
            </div>
            <div class="row pb-3 border-bottom">
                <div class="col-4">
                    Shipping
                </div>
                <div class="col-4 offset-4">
                    $19.99
                </div>
                <!--endrow-->
            </div>
            <div class="row pb-3 ">
                <div class="col-4">
                    <h6>Total </h6>
                </div>
                <div class="col-4 offset-4">
                    <h6>$201.74</h6>
                </div>
                <!--endrow-->
            </div>
        </div>
        <!--endrow-->
    </div>
    <!--end main-->
</div>

AdventureWorks.CustomerCarePortal.Web/Views/Shared/_Layout.cshtml
@{
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]  Adventure Works</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs5/dt-1.12.1/datatables.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AdventureWorks.CustomerCarePortal.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <!--Nab Bar-->
    @await Html.PartialAsync("~/Views/Shared/_NavBar.cshtml")
    <!--Nab Bar-->
    <div id="main" class="container-fluid">
        <div class="row">
            <!--Side Bar-->
            @await Html.PartialAsync("~/Views/Shared/_SideBar.cshtml")
            <!--Side Bar-->
            <main role="main" class="pb-3 col-7 ms-5">
                @RenderBody()
            </main>
        </div>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - AdventureWorks - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    @*TODO: Scope js to views*@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/v/bs5/dt-1.12.1/datatables.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

AdventureWorks.CustomerCarePortal.Web/Views/Shared/_NavBar.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Adventure Works</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" 
            data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Customer" asp-action="Index">Customer Details</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Order" asp-action="Index">Order Details</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>

AdventureWorks.CustomerCarePortal.Web/Views/Shared/_SideBar.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    List<string> customers = new() { "bob jones", "terry albier", "sarah vaughn", "pat morris", "stefan aluez", 
                                    "jack horsey", "stacy gwen", "peter parker", "calahan fangs" };
    Random rnd = new Random();
}
<!--Sidebar-->
<div class="col-3 border-end">
    <div class="d-flex flex-column align-items-stretch flex-shrink-0 bg-white">
        <a href="/" class="d-flex align-items-center flex-shrink-0 p-3 link-dark text-decoration-none border-bottom">
            <svg class="bi pe-none me-2" width="30" height="24"><use xlink:href="#bootstrap"></use></svg>
            <span class="fs-5 fw-semibold">Customer Care</span>
        </a>
        <div id="customer-list-group" class="list-group list-group-flush border-bottom scrollarea">
            <a href="#" class="list-group-item  customer-list-group-item list-group-item-action 
            active py-3 lh-sm justify-content-between" aria-current="true">
                <div class="row">
                    <div class="col-1 offset-10">
                        <small class="customer-list-closeButton">&#10060;</small>
                    </div>
                </div>
                <div class="row mr-5 mt-1">
                    <div class="col-5">Default Customer</div>
                    <div class="col-1 offset-5">84</div>
                </div>
            </a>
            @for (int i = 0; i < @customers.Count - 1; i++)
            {
                <a href="#" id=@($"list-group-item-{i}") class="list-group-item  customer-list-group-item
                list-group-item-action  py-3 lh-sm justify-content-between" aria-current="true">
                    <div class="row">
                        <div class="col-1 offset-10">
                            <small class="customer-list-closeButton">&#10060;</small>
                        </div>
                    </div>
                    <div class="row mr-5 mt-1">
                        <div class="col-5">@customers[i]</div>
                        <div class="col-1 offset-5">@rnd.Next(99)</div>
                    </div>
                </a>
            }
        </div>
    </div>
</div>
<!--Sidebar-->